### ISSUE TITLE
vh and vw unit does not works on eink kobo

### ISSUE THREAD

**Issue by mrbbp** [kobolabs/epub-spec#53]
```css
html, body {
      width: 100vw;
      height: 100vh;
      overflow: hidden;
      background-color: black;
    }
    main {
      position: absolute;
      background-color: white;
      color: black;
      width: calc(100vw - 2rem);
      height: calc(100vh - 2rem);
      margin: 1rem;
    }
```

if i use `width: calc(100% - 2rem);`, it works!
